course/urls.py
from django.conf.urls import url

from .views import CourseListView, CourseCreateView, CourseDeleteView, CourseUpdateView

app_name = 'course'
urlpatterns = [
    url(r'^$', CourseListView.as_view(), name='list'),
    url(r'^create$', CourseCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/update$', CourseUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete$', CourseDeleteView.as_view(), name='delete'),
]

grade/urls.py
from django.conf.urls import url

from .views import GradeListView, GradeCreateView, GradeUpdateView, GradeDeleteView

app_name = 'grades'
urlpatterns = [
    url(r'^$', GradeListView.as_view(), name='list'),
    url(r'^create$', GradeCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/update$', GradeUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete$', GradeDeleteView.as_view(), name='delete'),
]

minisql/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import Home

urlpatterns = [
    url(r'^$', Home.as_view(), name='home'),
    url(r'^users/', include('users.urls')),
    url(r'^course/', include('course.urls')),
    url(r'^grades/', include('grade.urls')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

app_name = 'users'
urlpatterns = [
    url(r'^login$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout$', logout, {'template_name': 'users/logout.html'}, name='logout'),
]

course/models.py
from __future__ import unicode_literals

from django.db import models


class Course(models.Model):
    topic = models.CharField(max_length=255)
    teacher = models.ForeignKey('users.Teacher')
    students = models.ManyToManyField('users.Student')

    def __unicode__(self):
        return u"{} - {}".format(self.topic, self.teacher)

grade/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _


class Grade(models.Model):
    grade_choices = (
        [str(i) + sign, str(i) + sign]
        for i in range(1, 7)
        for sign in ['', '+', '-']
        if not (i == 1 and sign == '-') and not (i == 6 and sign == '+')
    )
    student = models.ForeignKey('users.Student', null=True)
    teacher = models.ForeignKey('users.Teacher', null=True)
    course = models.ForeignKey('course.Course')
    grade = models.CharField(verbose_name=_('Grade'), choices=grade_choices, max_length=3)

users/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(verbose_name=_('Departament'), max_length=100, blank=True, null=True)

    def __unicode__(self):
        return u"{} - {} {} @ {}".format(self.user.username, self.user.first_name, self.user.last_name, self.department)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __unicode__(self):
        return u"{} - {} {}".format(self.user.username, self.user.first_name, self.user.last_name)

course/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django_tables2 import SingleTableView
from grade.views import TeacherViewMixin

from .models import Course
from .tables import CourseTable


class CourseListView(LoginRequiredMixin, SingleTableView):
    model = Course
    table_class = CourseTable

    def get_queryset(self):
        qs = super(CourseListView, self).get_queryset()
        user = self.request.user
        if hasattr(user, 'student'):
            qs = qs.filter(students=user.student)
        if hasattr(user, 'teacher'):
            qs = qs.filter(teacher=user.teacher)
        return qs


class CourseCreateView(TeacherViewMixin, CreateView):
    model = Course
    fields = ('topic', 'students')
    success_url = reverse_lazy('course:list')

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.teacher = self.request.user.teacher
        return super(CourseCreateView, self).form_valid(form)


class CourseUpdateView(TeacherViewMixin, UpdateView):
    model = Course
    fields = ('topic', 'students')
    success_url = reverse_lazy('course:list')

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.teacher = self.request.user.teacher
        return super(CourseUpdateView, self).form_valid(form)


class CourseDeleteView(TeacherViewMixin, DeleteView):
    model = Course
    success_url = reverse_lazy('course:list')

grade/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django_tables2 import SingleTableView

from .models import Grade
from .tables import GradeTable


class GradeListView(LoginRequiredMixin, SingleTableView):
    model = Grade
    table_class = GradeTable

    def get_queryset(self):
        qs = super(GradeListView, self).get_queryset()
        user = self.request.user
        if hasattr(user, 'student'):
            qs = qs.filter(student=user.student)
        if hasattr(user, 'teacher'):
            qs = qs.filter(teacher=user.teacher)
        return qs


class TeacherViewMixin(UserPassesTestMixin, LoginRequiredMixin):
    def test_func(self):
        return hasattr(self.request.user, 'teacher')


class GradeCreateView(TeacherViewMixin, CreateView):
    model = Grade
    fields = ('student', 'grade', 'course')
    success_url = reverse_lazy('grades:list')

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.teacher = self.request.user.teacher
        return super(GradeCreateView, self).form_valid(form)


class GradeUpdateView(TeacherViewMixin, UpdateView):
    model = Grade
    fields = ('student', 'grade', 'course')
    success_url = reverse_lazy('grades:list')

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.teacher = self.request.user.teacher
        return super(GradeUpdateView, self).form_valid(form)


class GradeDeleteView(TeacherViewMixin, DeleteView):
    model = Grade
    success_url = reverse_lazy('grades:list')

minisql/views.py
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = 'home.html'

course/templates/course/course_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
</form>
{% endblock %}

course/templates/course/course_form.html
{% extends "base.html" %}

{% load bootstrap3 %}


{% block content %}
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary pull-right">
            {% bootstrap_icon "submit" %} Submit
        </button>
    {% endbuttons %}
</form>
{% endblock %}

course/templates/course/course_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block content %}
    {% if request.user.teacher %}
        <a class="btn btn-primary pull-right" href="{% url "course:create" %}"> + Create Course</a>
    {% endif %}
{% render_table table %}
{% endblock %}

grade/templates/grade/grade_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
</form>
{% endblock %}

grade/templates/grade/grade_form.html
{% extends "base.html" %}

{% load bootstrap3 %}


{% block content %}
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary pull-right">
            {% bootstrap_icon "submit" %} Submit
        </button>
    {% endbuttons %}
</form>
{% endblock %}

grade/templates/grade/grade_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block content %}
    {% if request.user.teacher %}
        <a class="btn btn-primary pull-right" href="{% url "grades:create" %}"> + Create Grade</a>
    {% endif %}
{% render_table table %}
{% endblock %}

minisql/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bootstrap 3 Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap core CSS -->
    <link href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet" media="screen">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      {% include "menu.html" %}


        {% block content %}
             <!-- Main component for a primary marketing message or call to action -->
              <div class="jumbotron">
                <h1>Hello to my minisql</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque commodi eius expedita quos voluptatem! Architecto consectetur corporis doloribus dolorum ducimus eligendi, ipsam molestiae molestias neque non, omnis, possimus. Culpa, necessitatibus.</p>
              </div>
        {% endblock %}

    </div> <!-- /container -->


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>

minisql/templates/django_tables2/table.html
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}
{% load bootstrap3 %}

{% if table.page %}
    <style>

        .table-container th.asc:after {
          content: '\0000a0\0025b2';
        }
        .table-container th.desc:after {
          content: '\0000a0\0025bc';
        }
        .pagination {
          text-align: center;
        }
    </style>
    <div class="table-container">
{% endif %}

{% block table %}
    <table class="table table-compact table-bordered"{% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
        {% block table.thead %}
            <thead>
            <tr>
                {% for column in table.columns %}
                    {% if column.orderable %}
                        <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a></th>
                    {% else %}
                        <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
                    {% endif %}
                {% endfor %}
            </tr>
            </thead>
        {% endblock table.thead %}
        {% block table.tbody %}
            <tbody>
            {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
                {% block table.tbody.row %}
                    <tr class="{% cycle "odd" "even" %}">
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{{ cell }}</td>
                        {% endfor %}
                    </tr>
                {% endblock table.tbody.row %}
            {% empty %}
                {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                {% endif %}
            {% endfor %}
            </tbody>
        {% endblock table.tbody %}
        {% block table.tfoot %}
            <tfoot></tfoot>
        {% endblock table.tfoot %}
    </table>
{% endblock table %}

{% if table.page %}
    {% block pagination %}
        {% bootstrap_pagination table.page url=request.get_full_path parameter_name=table.prefixed_page_field %}
    {% endblock pagination %}
{% endif %}

minisql/templates/home.html
{% extends "base.html" %}

minisql/templates/menu.html
<!-- Static navbar -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">MiniSQL</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                <li><a href="{% url "grades:list" %}">Grades</a></li>
                <li><a href="{% url "course:list" %}">Courses</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url "users:logout" %}">Logout {{ request.user.username }}</a></li>
                {% else %}
                    <li><a href="{% url "users:login" %}">Login</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>

users/templates/users/login.html
{% extends "base.html" %}

{% load bootstrap3 %}


{% block content %}
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary pull-right">
            {% bootstrap_icon "submit" %} Submit
        </button>
    {% endbuttons %}
</form>
{% endblock %}

users/templates/users/logout.html
{% extends "base.html" %}

{% block content %}
{% endblock %}